package torch

const (
	HASH_LEN = 20
	KEY_LEN  = 16
)

const (
	PAYLOAD_LEN   = 509
	CIRCID_LEN_v1 = 2
	CIRCID_LEN_v4 = 4
)

const (
	CELL_PADDING = iota
	CELL_CREATE
	CELL_CREATED
	CELL_RELAY
	CELL_DESTROY
	CELL_CREATE_FAST
	CELL_CREATED_FAST
	CELL_VERSIONS // variable-length
	CELL_NETINFO
	CELL_RELAY_EARLY
	CELL_CREATE2
	CELL_CREATED2
)

const (
	CELL_VPADDING = 128 + iota
	CELL_CERTS
	CELL_AUTH_CHALLENGE
	CELL_AUTHENTICATE
	CELL_AUTHORIZE
)

const (
	RELAY_BEGIN = 1 + iota
	RELAY_DATA
	RELAY_END
	RELAY_CONNECTED
	RELAY_SENDME
	RELAY_EXTEND
	RELAY_EXTENDED
	RELAY_TRUNCATE
	RELAY_TRUNCATED
	RELAY_DROP
	RELAY_RESOLVE
	RELAY_RESOLVED
	RELAY_BEGIN_DIR
	RELAY_EXTEND2
	RELAY_EXTENDED2
)

const (
	RELAY_ESTABLISH_INTRO = 32 + iota
	RELAY_ESTABLISH_RENDEZVOUS
	RELAY_INTRODUCE1
	RELAY_INTRODUCE2
	RELAY_RENDEZVOUS1
	RELAY_RENDEZVOUS2
	RELAY_INTRO_ESTABLISHED
	RELAY_RENDEZVOUS_ESTABLISHED
	RELAY_INTRODUCE_ACK
)

const (
	REASON_MISC = 1 + iota
	REASON_RESOLVEFAILED
	REASON_CONNECTREFUSED
	REASON_EXITPOLICY
	REASON_DESTROY
	REASON_DONE
	REASON_TIMEOUT
	REASON_NOROUTE
	REASON_HIBERNATING
	REASON_INTERNAL
	REASON_RESOURCELIMIT
	REASON_CONNRESET
	REASON_TORPROTOCOL
	REASON_NOTDIRECTORY
)

const (
	RELAY_PAYLOAD_LEN = PAYLOAD_LEN - 11
)
